// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.30.2

/* eslint-disable */

export * as protobuf from "./index.google.protobuf";
